qv/core schema 2
apollographql/core-schema-js pull request #3
Opened 2021-07-22 01:01 UTC by queerviolet

substantially simplified from #1.

gone:
  - `data` and `derive`
  -  `serde`

still here: caching of some kind. there is now a `CoreSchema` abstraction which holds (1) a document ast and (2) helpers for various common tasks, like `core.read`ing all the metadata for a feature url from a node, and (3) a cache of data derived from that ast, keyed by the function which produces them. in their simplest form, these functions take a `CoreSchema` and return some value derived from it.

they may also be declared as taking a `CoreSchemaContext` to access additional methods: `core.pure` and `core.report`.

`core.report` reports an error (you can also report an error by `throw`ing it, but then you can just report one)

`core.pure` declares that the remainder of function execution is a pure function of its arguments. if the containing function has been executed before and the arguments are identical to that time, evaluation is halted and the previous value is used.

for instance, `names`, which derives and validates the map of names to features, uses this to gate on the features having changed:
```typescript
export function names(this: CoreSchemaContext) {
  const {features} = this
  this.pure(features)
...
```

the `features` function calls it on the schema's directives, which are all it cares about:

```typescript
export function features(this: CoreSchemaContext) {
  const schema = this.schema
  this.pure(...schema.directives ?? [])
...
```

this allows `core.update` to have no fancy cache invalidation logic whatsoever: the cache is allowed to be stale until a layer is read again, at which point it will re-evaluate its derived data.

the intention here is that other functions which want to derive data from the ast (for example, to support `join` or other features) can use this as well.

2021-07-22 01:12 UTC, queerviolet commented
should note that the motivation to cache derived metadata isn't purely to avoid work. rather, if we report errors while extracting data (i.e. report overlapping names while extracting names), it's difficult to avoid reporting the same error on the document multiple times. this solves that.

2021-07-22 01:15 UTC, glasser commented
I appreciate being consulted but I'll be heading on vacation for a few weeks in a couple days. I might have time this week to look but likely not. Very excited that this is happening though!

2021-07-22 13:18 UTC, martijnwalraven reviewed
I'm going to limit myself to some high-level feedback for now. Really happy we're tackling this, because the ad-hoc way we've been handling Core Schema so far is pretty janky.

My main worry is that this ties Core Schema processing to the `graphql-js` AST, while in parallel we're working on [a new schema abstraction in `@apollo/core`](https://github.com/apollographql/federation-private/pull/69/commits/71d2a3019f0c9cf733030257046bb19a2d2ce06b).

That code is work in progress, and the API is very much up for discussion. But I do think Core Schema processing should be integrated into that library, so even if we want to release an AST-based `core-schema-js` first we should start thinking about the scenarios we want to support with `@apollo/core` to avoid painting ourselves in a corner.

For example, the current `@apollo/core` allows you to iterate over all schema elements, and remove elements that have `@inaccessible` applied with code like this (while keeping track of backreferences for cascading removals, but leaving that out for now):

```typescript
for (const element of schema.allNamedSchemaElements()) {
  if (element.hasAppliedDirective(inaccessibleDirective)) {
    element.remove();
  }
}
```

That code doesn't currently know how to collect features or deal with namespaced directives. Unfortunately, `core-schema-js` won't help with that either, because the AST is not the source of truth here.

We've brainstormed about possible APIs for handling Core Schema, imagining code like:

```typescript
const tagDirective = schema.getFeature('https://specs.apollo.dev/tag/v0.1')?.getRootDirective();
if (!tagDirective) return;

const inaccessibleDirective = schema.getOrAddFeature('https://specs.apollo.dev/inaccessible/v0.1')?.getRootDirective();

for (const element of schema.allElements()) {
  const tags = element.getAppliedDirectives(tagDirective);
  if (!tags) continue;

  if (shouldMarkAsInaccessible(tags)) {
    element.applyDirective(inaccessibleDirective);
  }
}
```

Definitely not saying that's what things should look like, but I do think letting go of the requirement that Core Schema processing has to be built directly on top of the AST could improve the developer experience and even simplify the implementation. 

For example, having our own `Schema` class allows us to store collected features in a normal instance variable, and we can precompute other semantic information as well (just as we do for backreferences). If we still want on demand caching, for keeping track of elements that have certain feature directives applied for example, that could be implemented as a memoized method. With that, I think we could avoid the need for a hooks-like generic caching mechanism altogether.

2021-07-22 14:35 UTC, queerviolet commented
why not have that new work should leverage this rather than the other way around? reasoning:
1. the ast, at some point, _is_ the source of truth
2. the ast is also constructed of immutable objects, whereas the new layer is about providing new mutable containers. generally building mutable containers atop immutable objects makes 
3. this… exists?

2021-07-22 19:49 UTC, abernix requested changes
This is looking good and I'm leaning strongly toward LGTM.  Currently _requesting changes_, but I don't think it'll be particularly hard to get it over the line delta writing some tests.  Some thoughts:

- I'm concerned that there is one library trying to build a `@apollo/core` and this is `@apollo/core-schema`.  If anything, _this_ PR seems like it could be `@apollo/core` — it's a core schema because it has core features in it, but it finds core features from a schema?  Curious how you landed here.  (Also, we _should_ have captured / agreed on this in Statement of Work / Design ahead of time, but we can do that next time).
- Tests. There are many more implementations other than just the ones I noted that need tests.  I think the Public API in particular should all be tested.
- The AST seems like a fine structure to build this around, but I do think it's worth honoring a conversation about whether that will be the only desire and discussing inter-op with The Other Thing.  My read on @martijnwalraven's comment was that it was also suggesting we _ship_ this and have discussions soon.  We had an opportunity to have the conversation sooner, but I don't know that we did.
- I have a comment about the caching implementation which asks for an npm-market-analysis of possibly already complete/tested solutions.  This new package currently has _no_ runtime dependencies right now, which is a feat, but I'd claim that we could afford to have one if it's saving us code and tests _or_ we should include a rational for why not.  (More in comment noted below).

Happy to review again tomorrow in what I believe to be everyone else's absence (assuming it's before I run into the weekend, otherwise first thing Monday for sure.)

Thanks for putting this together! I'm certainly excited to stop being so blunt with what've had to implement so far.

2021-07-22 19:49 UTC, abernix commented on src/schema.ts
> +export function features(this: CoreSchemaContext) {
Ok, lots of asks by me as this point for explicit type return values.  curious as to your perspective for omitting them here because it does make it more difficult to fly-by understand without an active language server and i do think it's defensive in a good checksum-kinda-way as code evolves.

2021-07-22 19:49 UTC, abernix commented on src/schema.ts
> +
There's some chunks of relatively complex repetition with some subtle differences between this and the `*read` generator function above on `CoreSchema`.  It's not so much that it shocks the conscious by any means, but there seem like there could be some utilities to abstract?  Not a hard ask.  My ask would be tests that would hopefully ensure functional parity.

2021-07-22 22:47 UTC, queerviolet commented
so, a quick answer to the question of "why did we write core.ts rather than picking something off npm", i looked at `memoize`, `memoizee`, and `fast-memoize` and then gave up. none of them provide exactly what we're doing here. in particular, none of them memoize _failures_, and none of them provide a way to report multiple errors. (i also wouldn't expect an off-the-shelf memoization library to support multiple errors, it's rather specific to graphql).

they also don't support anything like `pure`, having other (more intrusive*, imo) ways to describe the cache key. i expect that some of them could be roped into providing equivalent behavior, but i didn't see anything else that would let us say, in the middle of doing stuff, "hey, if <some stuff> hasn't changed since last time, just use the previous result". the functional programming answer to that is that your function is too big and you should break it into multiple parts. but like many functional programming answers, actually doing that is sometimes very annoying, especially if you want the types of those functions to be reasonable.

* — a word on "more intrusive": a nice quality of this approach is that if you want to switch off caching, or call a `CoreFn` without a core, you can just provide a context where `pure` does nothing, and `get` returns `fn(this)`.

2021-07-22 22:50 UTC, queerviolet commented on README.md
> +const example = CoreSchema.graphql`
i wanted a tagged literal function, mainly for tests / demos, and i wanted something to distinguish it from `fromSource`, though of course `fromSource` could just be very overloaded. given that it's a tag function, giving it the name of the language it's parsing seemed to telegraph that fact. but i'm hardly very set on it. is there a particular alternative you'd prefer?

2021-07-22 23:23 UTC, queerviolet commented on src/core.ts
> +      throw ErrNoLayerData(cell.result.errors)
done

2021-07-22 23:23 UTC, queerviolet commented on src/core.ts
> +    if (!top) throw ErrEvalStackEmpty()
done

2021-07-22 23:25 UTC, queerviolet commented on src/error.ts
> +    }
yeah, we can't re-assign e.g. `source`, it's already set in the constructor. renamed this to `BASE_PROPS`, which i think makes more sense?

2021-07-22 23:25 UTC, queerviolet commented on src/schema.ts
> +  }
i think that is correct, the tagged literal is mostly nice for tests / quick demos. but it is rather nice for those things.

2021-07-22 23:27 UTC, queerviolet commented on src/schema.ts
> +  *read(directive: GraphQLDirective | FeatureUrl | string, node: ASTNode) {
i added it, but are you sure you want this? the type of a generator function is rather odd-looking (it is not, for some reason, `Iterator<Item>`)

2021-07-22 23:28 UTC, queerviolet commented on src/schema.ts
> +  *read(directive: GraphQLDirective | FeatureUrl | string, node: ASTNode) {
there are tests of it, though i agree there could be more

2021-07-22 23:30 UTC, queerviolet commented on src/schema.ts
> +export function features(this: CoreSchemaContext) {
mainly i just add types when typescript tells me it needs them. also they _have_ to be there in the class, and the class just calls into these functions, so it didn't seem that important. but it's also fine to have them

2021-07-22 23:36 UTC, queerviolet commented on src/error.ts
> +}
correct. it also ensure that all errors have a code, and does it in such a way that you can say `if (err.code == 'SomeCode') err.someExtensionProp...` and have the types come out correctly.

2021-07-22 23:36 UTC, queerviolet commented on src/error.ts
> +}
(added a comment to that effect)

2021-07-22 23:37 UTC, queerviolet commented on package.json
> +  "name": "@apollo/core-schema",
yeah i kindof think you're right that *this* should be `@apollo/core` and the mutable jQuery-ish library should be `@apollo/core-schema`.

2021-07-22 23:37 UTC, queerviolet commented on package.json
> +    "prettier": "^2.2.1",
yes.

2021-07-22 23:37 UTC, queerviolet commented on package.json
> +    "binarysearch": "^1.0.1"
done

2021-07-22 23:39 UTC, queerviolet commented on src/core.ts
> +  getResult<F extends CoreFn<this>>(fn: F): Result<ReturnType<F>> {
the short answer is that it lets you do a bunch of stuff and then get the list of errors without throwing them, which there otherwise isn't a way to do.

but maybe, if we haven't needed it here, we don't need it?

2021-07-22 23:40 UTC, queerviolet commented on src/feature-url.ts
> +    return `${this.identity}/${this.version}`
the forcing comes in via a redirect, right? like if i go to the url without the trailing slash, netlify will add it? or no?

2021-07-26 20:40 UTC, queerviolet commented on src/core.ts
> +  }
added tests

2021-07-26 20:40 UTC, queerviolet commented on src/features.ts
> +  private findOrCreateIdentity(identity: string) {
done

2021-07-26 21:00 UTC, queerviolet commented on src/schema.ts
> +
`reader` was unused, removed

2021-07-26 21:34 UTC, queerviolet commented on src/feature-url.ts
> +  public static parse(input: string, node?: ASTNode): FeatureUrl {
done

2021-07-26 21:35 UTC, queerviolet commented on src/core.ts
> +export type Immutable<T> = Omit<T, 'update'>
i tend to avoid type parameter constraints where they're not necessary, but sure

2021-07-26 21:35 UTC, queerviolet commented on src/core.ts
> +  }
(see comment on why this exists at all)

2021-07-26 21:36 UTC, queerviolet commented on src/is.ts
> +export type Template = Parameters<typeof String.raw>
added tests

2021-07-26 21:36 UTC, queerviolet commented on src/version.ts
> +   * ```
done

2021-07-26 21:36 UTC, queerviolet commented on src/version.ts
> +   * assert(!(new Version(2, 0).satisfies(new Version(1, 9))))
done

2021-07-26 21:36 UTC, queerviolet commented on src/version.ts
> +// TODO: Convert tests
done

2021-07-27 00:56 UTC, queerviolet commented on src/schema.ts
> +  }
quick note that currently, you have to say `CoreSchema.fromSource(new Source(stringVariable, filenameOrUrl))`, but that seems maybe not bad. you most likely did just get the `stringVariable` from somewhere, and this will attach that somewhere to the ast so it shows up in errors

2021-07-27 17:48 UTC, abernix approved these changes
LGTM! None of my comments need addressing necessarily. :shipit: 

I do really enjoy the patterns you adopted here in this v. of the PR; the code is crisp and well tested.

2021-07-27 17:48 UTC, abernix commented on src/__tests__/feature-url.test.ts
> +        `"expected a version specifier like \\"v9.8\\", got \\"core\\""`
This is the only error message that struck me as being a bit off, since it seems to me that it would not get `core`, but that it just _didn't get anything_.  Not asking for a fix, but also just curious if this is a sign of anything to worry about adjusting in implementation.

2021-07-27 17:48 UTC, abernix commented on src/__tests__/version.test.ts
> +        `"expected a version specifier like \\"v9.8\\", got \\"bloop\\""`
Can confirm, is bloop.

2021-07-27 17:48 UTC, abernix commented on src/error.ts
> + * these errors to be a tagged union.
❤️

2021-07-27 17:48 UTC, abernix commented on src/feature-url.ts
> +    message: `feature url does not have a path: ${url}`,
Definitely appreciate this change.

2021-07-27 17:48 UTC, abernix commented on src/version.ts
> +   * return true iff this version is exactly equal to the provided version
intentional _if and only if_ (iff) or typo? (I think desired implied by _strict_ below).

2021-07-28 23:22 UTC, queerviolet commented on src/version.ts
> +   * return true iff this version is exactly equal to the provided version
intentional if and only if

2021-07-28 23:23 UTC, queerviolet commented on src/__tests__/feature-url.test.ts
> +        `"expected a version specifier like \\"v9.8\\", got \\"core\\""`
oh, mmm. it's just that it tries to interpret a single path element as a version specifier

we should probably just make it throw `NoPath` in this case, since less than two path segments can't be a valid feature url. i'll open that as a separate issue.

2021-07-28 23:24 UTC, merged